### ISSUE TITLE
报错 /Web-Conf/node_modules/web-cell/source/renderer.ts:39:21: Cannot resolve dependency 'snabbdom/build/package/init'

### ISSUE THREAD

**Issue by luojiyin1987** [FreeCodeCamp-Chengdu/Web-Conf#44]
是否还要安装对应的 type 文件？
运行  pnpm start  出现如上报错。
详细报错信息
系统 Ubuntu 22.04 
node 版本 16.19.0
npm 版本  8.19.3

```shell
npm start   

> web-conf@3.1.0 start
> parcel source/index.html --open

Server running at http://localhost:1234 
🚨  /home/luo/nodeWork/Web-Conf/node_modules/web-cell/source/renderer.ts:39:21: Cannot resolve dependency 'snabbdom/build/package/init'
    at Resolver.resolve (/home/luo/nodeWork/Web-Conf/node_modules/.pnpm/registry.npmmirror.com+parcel-bundler@1.12.5/node_modules/parcel-bundler/src/Resolver.js:71:17)
    at async Bundler.resolveAsset (/home/luo/nodeWork/Web-Conf/node_modules/.pnpm/registry.npmmirror.com+parcel-bundler@1.12.5/node_modules/parcel-bundler/src/Bundler.js:433:18)
    at async Bundler.resolveDep (/home/luo/nodeWork/Web-Conf/node_modules/.pnpm/registry.npmmirror.com+parcel-bundler@1.12.5/node_modules/parcel-bundler/src/Bundler.js:484:14)
    at async /home/luo/nodeWork/Web-Conf/node_modules/.pnpm/registry.npmmirror.com+parcel-bundler@1.12.5/node_modules/parcel-bundler/src/Bundler.js:608:26
    at async Promise.all (index 2)
    at async Bundler.loadAsset (/home/luo/nodeWork/Web-Conf/node_modules/.pnpm/registry.npmmirror.com+parcel-bundler@1.12.5/node_modules/parcel-bundler/src/Bundler.js:599:21)
    at async /home/luo/nodeWork/Web-Conf/node_modules/.pnpm/registry.npmmirror.com+parcel-bundler@1.12.5/node_modules/parcel-bundler/src/Bundler.js:610:13
    at async Promise.all (index 3)
    at async Bundler.loadAsset (/home/luo/nodeWork/Web-Conf/node_modules/.pnpm/registry.npmmirror.com+parcel-bundler@1.12.5/node_modules/parcel-bundler/src/Bundler.js:599:21)
    at async /home/luo/nodeWork/Web-Conf/node_modules/.pnpm/registry.npmmirror.com+parcel-bundler@1.12.5/node_modules/parcel-bundler/src/Bundler.js:610:13
    at async Promise.all (index 4)
    at async Bundler.loadAsset (/home/luo/nodeWork/Web-Conf/node_modules/.pnpm/registry.npmmirror.com+parcel-bundler@1.12.5/node_modules/parcel-bundler/src/Bundler.js:599:21)
    at async /home/luo/nodeWork/Web-Conf/node_modules/.pnpm/registry.npmmirror.com+parcel-bundler@1.12.5/node_modules/parcel-bundler/src/Bundler.js:610:13
    at async Promise.all (index 2)
    at async Bundler.loadAsset (/home/luo/nodeWork/Web-Conf/node_modules/.pnpm/registry.npmmirror.com+parcel-bundler@1.12.5/node_modules/parcel-bundler/src/Bundler.js:599:21)
    at async Bundler.processAsset (/home/luo/nodeWork/Web-Conf/node_modules/.pnpm/registry.npmmirror.com+parcel-bundler@1.12.5/node_modules/parcel-bundler/src/Bundler.js:557:5)
    at async PromiseQueue._runJob (/home/luo/nodeWork/Web-Conf/node_modules/.pnpm/registry.npmmirror.com+parcel-bundler@1.12.5/node_modules/parcel-bundler/src/utils/PromiseQueue.js:48:7)
⚠️  Could not load source file "../src/index.ts" in source map of "../node_modules/html-to-image/es/index.js".
⚠️  Could not load source file "../src/clone-node.ts" in source map of "../node_modules/html-to-image/es/clone-node.js".
⚠️  Could not load source file "../src/embed-images.ts" in source map of "../node_modules/html-to-image/es/embed-images.js".
⚠️  Could not load source file "../src/apply-style.ts" in source map of "../node_modules/html-to-image/es/apply-style.js".
⚠️  Could not load source file "../src/embed-webfonts.ts" in source map of "../node_modules/html-to-image/es/embed-webfonts.js".
⚠️  Could not load source file "../src/util.ts" in source map of "../node_modules/html-to-image/es/util.js".
⚠️  Could not load source file "../src/clone-pseudos.ts" in source map of "../node_modules/html-to-image/es/clone-pseudos.js".
⚠️  Could not load source file "../src/mimes.ts" in source map of "../node_modules/html-to-image/es/mimes.js".
⚠️  Could not load source file "../src/dataurl.ts" in source map of "../node_modules/html-to-image/es/dataurl.js".
⚠️  Could not load source file "../src/embed-resources.ts" in source map of "../node_modules/html-to-image/es/embed-resources.js".
```
@TechQuery

**Comment by luojiyin1987** [comment]
是否需要 `npm i snabbdom`  将  snabbdom  安装到开发环境？

**Comment by luojiyin1987** [comment]
`npm i snabbdom -D`   报错消失

**Comment by luojiyin1987** [comment]
报错  /Web-Conf/node_modules/cell-router/source/History.ts:48:28: Cannot resolve dependency 'iterable-observer'
`npm i iterable-observer -D`  解决报错

**Comment by luojiyin1987** [comment]
浏览器打开网址无内容显示 

相关终端日志
```shell
Server running at http://localhost:1234 
⚠️  Could not load source file "../src/index.ts" in source map of "../node_modules/html-to-image/es/index.js".
⚠️  Could not load source file "../src/clone-node.ts" in source map of "../node_modules/html-to-image/es/clone-node.js".
⚠️  Could not load source file "../src/embed-images.ts" in source map of "../node_modules/html-to-image/es/embed-images.js".
⚠️  Could not load source file "../src/apply-style.ts" in source map of "../node_modules/html-to-image/es/apply-style.js".
⚠️  Could not load source file "../src/embed-webfonts.ts" in source map of "../node_modules/html-to-image/es/embed-webfonts.js".
⚠️  Could not load source file "../src/util.ts" in source map of "../node_modules/html-to-image/es/util.js".
⚠️  Could not load source file "../src/clone-pseudos.ts" in source map of "../node_modules/html-to-image/es/clone-pseudos.js".
⚠️  Could not load source file "../src/mimes.ts" in source map of "../node_modules/html-to-image/es/mimes.js".
⚠️  Could not load source file "../src/dataurl.ts" in source map of "../node_modules/html-to-image/es/dataurl.js".
⚠️  Could not load source file "../src/embed-resources.ts" in source map of "../node_modules/html-to-image/es/embed-resources.js".
✨  Built in 14.99s.
```

**Comment by TechQuery** [comment]
我前一阵也想在本地改一点东西，发现 WebCell 2 + Parcel 1 的很多深层依赖在全新安装时会不匹配，因为很多依赖包都很旧了，就在 GitHub 网页端简单改了一下。

2022 年春节我在家启动 [WebCell 3 + Parcel 2 的重写][1]，核心写好了，也[更好用][2]。但因为忙了一整年，[组件库还没升级完](url)，组件太多了。

[1]: https://github.com/orgs/EasyWebApp/projects/1?fullscreen=true
[2]: https://github.com/EasyWebApp/WebCell/blob/main/Migrating.md
[3]: https://github.com/EasyWebApp/BootCell/issues
